//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerDashboard
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CustomerId { get; set; }
        [Required]
        [Display(Name = "First Name")]
        [StringLength(25)]
        public string CustFirstName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        [StringLength(25)]
        public string CustLastName { get; set; }
        [Required]
        [Display(Name = "Address")]
        [StringLength(75)]
        public string CustAddress { get; set; }
        [Required]
        [Display(Name = "City")]
        [StringLength(50)]
        public string CustCity { get; set; }
        [Required]
        [Display(Name = "Province")]
        [StringLength(2)]
        public string CustProv { get; set; }
        [Required]
        [Display(Name = "Postal Code")]
        [StringLength(7)]
        [RegularExpression(@"[ABCEGHJKLMNPRSTVXY][0-9][ABCEGHJKLMNPRSTVWXYZ] ?[0-9][ABCEGHJKLMNPRSTVWXYZ][0-9]", ErrorMessage = "Not a valid postal code")]
        public string CustPostal { get; set; }
        [Required]
        [Display(Name = "Country")]
        [StringLength(25)]
        public string CustCountry { get; set; }
        [Required]
        [Display(Name = "Home Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string CustHomePhone { get; set; }


        [Display(Name = "Business Phone")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid phone number")]
        public string CustBusPhone { get; set; } = "";


        [Display(Name = "Email address")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string CustEmail { get; set; } = "";
        public Nullable<int> AgentId { get; set; }

        [Required]
        [Display(Name = "Password")]
        [StringLength(10)]
        public string CustPassword { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Re-enter Password")]
        [Compare("CustPassword", ErrorMessage = "Passwords do not match.")]
        public string ComparePassword { get; set; }
    }

    public enum CustProv
    {
        AB,
        BC,
        MB,
        NB,
        NL,
        NT,
        NS,
        NU,
        ON,
        PE,
        QC,
        SK,
        YT
    }
}

